# Generated by Django 5.1.1 on 2024-10-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_toko', '0004_rumahmakan_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
