# Generated by Django 5.1.2 on 2024-10-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_makanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko_makanan.toko'),
        ),
    ]
