# Generated by Django 5.1.2 on 2024-10-24 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_makanan', '0004_alter_makanan_id_alter_toko_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toko',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
