# Generated by Django 5.1.2 on 2024-10-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko_makanan', '0005_alter_makanan_id_alter_toko_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='description',
        ),
    ]
