# Generated by Django 5.1.2 on 2024-10-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RumahMakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.IntegerField()),
                ('nama_provinsi', models.CharField(max_length=100)),
                ('bps_kode_kabupaten_kota', models.IntegerField()),
                ('bps_nama_kabupaten_kota', models.CharField(max_length=100)),
                ('nama_rumah_makan', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tahun', models.IntegerField()),
                ('masakan_dari_mana', models.CharField(max_length=50)),
                ('makanan_berat_ringan', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorit_toko',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='toko',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='nama',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='harga',
        ),
        migrations.AddField(
            model_name='makanan',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makanan',
            name='rumah_makan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='makanan', to='main.rumahmakan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Toko',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
