# Generated by Django 5.1.2 on 2024-10-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_favorite_store', '0002_alter_userprofile_favorit_toko_delete_makanan_and_more'),
        ('main', '0002_rumahmakan_remove_userprofile_favorit_toko_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumah_makan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rumahmakan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
