# Generated by Django 5.1.2 on 2024-10-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.makanan'),
        ),
    ]
