# Generated by Django 5.1.4 on 2024-12-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='author',
            new_name='author_id',
        ),
    ]
